var R = randomNumber(0,235);
var G = randomNumber(0,235);
var B = randomNumber(0,235);
var color = rgb(R, G, B);
var randButtonId;
var buttonId;
var currentPlayer;
var p1Score;
var p2Score;

p1Score =0;
var R = randomNumber(0,235);
var G = randomNumber(0,235);
var B = randomNumber(0,235);
var color = rgb(R, G, B);
var randButtonId;
var buttonId;
var currentPlayer;
var p1Score;
var p2Score;

p1Score =0;
p2Score =0;

R = R+20;  
G = G+20;
B = B+20;
var diffColor = rgb(R, G, B);

setBoard();
checkCorrect();
updateScoreBy(123);

 if( buttonId == randButtonId ) {
        console.log("You got it right!");
    } else {
        console.log("WRONG");
    }
function setBoard(){
setProperty("button1", "background-color", color);
var diffColor = rgb(250, 175, 20, 0.5);
setProperty("button2", "background-color", diffColor);
var diffColor = rgb(250, 175, 20, 0.5);
setProperty("button3", "background-color", diffColor);
var diffColor = rgb(250, 175, 20, 0.5);
setProperty("button4", "background-color", diffColor);
var diffColor = rgb(250, 175, 20);
randButtonId = "button"+randomNumber(1,4);  
setProperty(randButtonId, "background-color", diffColor); 
console.log("correct one is:" + randButtonId);
}
function switchPlayer(){
    if(currentPlayer==1){
        currentPlayer=2;
       hideElement("player1_highlight");
       showElement("player2_highlight");
    } else {
        currentPlayer=1;
        hideElement("player2_highlight");
        showElement("player1_highlight");
    }
    console.log("current player is: "+currentPlayer);
}
function checkCorrect(buttonId){
    console.log("Checking: "+buttonId);
    setBoard();
    switchPlayer();
}
function updateScoreBy(amt){
    if(currentPlayer == 1){
        p1Score = p1Score + amt;
    } else {
        p2Score = p2Score + amt;
    }
    console.log("P1 score: " + p1Score);
    console.log("P2 score: " + p2Score);
}
onEvent("button1", "click", function(){
    checkCorrect("button1");
});
onEvent("button2", "click", function(){
    checkCorrect("button2");
});
onEvent("button3", "click", function(){
    checkCorrect("button3");
});
onEvent("button4", "click", function(){
    checkCorrect("button4");
});
